### ISSUE TITLE
using nginx reverse proxy in separate container, no css and images

### ISSUE THREAD

**Issue by Marthaarman** [ChatDeBlofeld/seafile-arm-docker-base#45]
I'm having my own nginx reverse proxy docker container and I want to "forward" a subdomain to the seafile setup (base).

Everything works except the webportal does not load stuff like images, js and css. 

nginx seafile.conf:

```
server {
    listen 80;
    listen [::]:80;
    server_name  storage.mydomain.com;
    rewrite ^ https://$http_host$request_uri? permanent;	# force redirect http to https
    server_tokens off;
}

server {
    listen 443;
    listen [::]:443 ssl http2;
    server_name storage.mydomain.com;

    # all ssl related config moved to ssl.conf
    ssl_certificate /etc/letsencrypt/live/storage.mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/storage.mydomain.com/privkey.pem;

    server_tokens off;

    location / {
        proxy_pass         http://seafile:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
        proxy_set_header   X-Forwarded-Proto https;

        proxy_read_timeout  1200s;

        client_max_body_size 0;
    }

    location /seafhttp {
        rewrite ^/seafhttp(.*)$ $1 break;
        proxy_pass http://seafile:8082;
        client_max_body_size 0;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
        proxy_send_timeout  36000s;
        send_timeout  36000s;
    }

    location /media {
        root /shared;
    }
} 

```

My nginx reverse proxy docker compose file:
```
version: "3.3"

services:
  nginx:
    container_name: 'nginx-service'
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - nginx_reverse_proxy
    restart: always

networks:
  nginx_reverse_proxy:
    driver: bridge
```

my seafile docker-compose.yml file:

```
version: '3'

services:
  db:
    image: linuxserver/mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=$TZ
    volumes:
      - ${DATABASE_DIR}:/config
    networks:
      - seafile

  seafile:
    depends_on:
      - db
    image: ${SEAFILE_IMAGE}
    restart: always
    ports:
      - 8000:8000/tcp
      - 8080:8080/tcp
      - 8082:8082/tcp
      - 8083:8083/tcp
    environment:
      - PUID=${PGID-}
      - PGID=${PUID-}
      - TZ=${TZ-}
      - SQLITE=${SQLITE-}
      - SERVER_IP=${HOST-}
      - PORT=${PORT-}
      - USE_HTTPS=${USE_HTTPS-}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL-}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD-}
      - MYSQL_HOST=${MYSQL_HOST:-db}
      - MYSQL_PORT=${MYSQL_PORT-}
      - USE_EXISTING_DB=${USE_EXISTING_DB-}
      - MYSQL_USER=${MYSQL_USER-}
      - MYSQL_USER_PASSWD=${MYSQL_USER_PASSWD-}
      - MYSQL_USER_HOST=${MYSQL_USER_HOST-}
      - MYSQL_ROOT_PASSWD=${MYSQL_ROOT_PASSWD-}
      - CCNET_DB=${CCNET_DB-}
      - SEAFILE_DB=${SEAFILE_DB-}
      - SEAHUB_DB=${SEAHUB_DB-}

    volumes:
      - media:/shared/media
      - ${SEAFILE_CONF_DIR}:/shared/conf
      - ${SEAFILE_LOGS_DIR}:/shared/logs
      - ${SEAFILE_DATA_DIR}:/shared/seafile-data
      - ${SEAFILE_SEAHUB_DIR}:/shared/seahub-data
    networks:
      - nginx_reverse_proxy
      - seafile

volumes:
  media:
  #~conf:
  #~logs:
  #~data:
  #~seahub:
  #~db:

networks:
  seafile:
  nginx_reverse_proxy:
    name: nginx_https_docker_nginx_reverse_proxy
    external: true

```

**Comment by ChatDeBlofeld** [comment]
Hi, that's because your nginx doesn't have access to those files. You'll have to share them between the containers with a volume, you can try something like this:


```yaml
# seafile docker-compose.yml

volumes:
  media:
    name: seafile-media
```

```yaml
# nginx docker-compose.yml

services:
  nginx:
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
      - seafile-media:/seafile-shared/media # <-- Note the new volume

volumes:
  seafile-media:
    external: true
```

```nginx
# seafile.conf

location /media {
  root /seafile-shared;
}
```

Note that I haven't tested it, but it should give you a decent hint.
